// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pb/master_cluster.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerRole int32

const (
	PeerRole_FOLLOWER     PeerRole = 0
	PeerRole_LEADER       PeerRole = 1
	PeerRole_CANDIDATE    PeerRole = 2
	PeerRole_UNKNOWN_ROLE PeerRole = 999
)

// Enum value maps for PeerRole.
var (
	PeerRole_name = map[int32]string{
		0:   "FOLLOWER",
		1:   "LEADER",
		2:   "CANDIDATE",
		999: "UNKNOWN_ROLE",
	}
	PeerRole_value = map[string]int32{
		"FOLLOWER":     0,
		"LEADER":       1,
		"CANDIDATE":    2,
		"UNKNOWN_ROLE": 999,
	}
)

func (x PeerRole) Enum() *PeerRole {
	p := new(PeerRole)
	*p = x
	return p
}

func (x PeerRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerRole) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_master_cluster_proto_enumTypes[0].Descriptor()
}

func (PeerRole) Type() protoreflect.EnumType {
	return &file_pb_master_cluster_proto_enumTypes[0]
}

func (x PeerRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PeerRole) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PeerRole(num)
	return nil
}

// Deprecated: Use PeerRole.Descriptor instead.
func (PeerRole) EnumDescriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{0}
}

type MasterErrorPB_Code int32

const (
	MasterErrorPB_UNKNOWN_ERROR  MasterErrorPB_Code = 1
	MasterErrorPB_INVALID_TABLE  MasterErrorPB_Code = 2
	MasterErrorPB_NOT_THE_LEADER MasterErrorPB_Code = 3
)

// Enum value maps for MasterErrorPB_Code.
var (
	MasterErrorPB_Code_name = map[int32]string{
		1: "UNKNOWN_ERROR",
		2: "INVALID_TABLE",
		3: "NOT_THE_LEADER",
	}
	MasterErrorPB_Code_value = map[string]int32{
		"UNKNOWN_ERROR":  1,
		"INVALID_TABLE":  2,
		"NOT_THE_LEADER": 3,
	}
)

func (x MasterErrorPB_Code) Enum() *MasterErrorPB_Code {
	p := new(MasterErrorPB_Code)
	*p = x
	return p
}

func (x MasterErrorPB_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MasterErrorPB_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_master_cluster_proto_enumTypes[1].Descriptor()
}

func (MasterErrorPB_Code) Type() protoreflect.EnumType {
	return &file_pb_master_cluster_proto_enumTypes[1]
}

func (x MasterErrorPB_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MasterErrorPB_Code) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MasterErrorPB_Code(num)
	return nil
}

// Deprecated: Use MasterErrorPB_Code.Descriptor instead.
func (MasterErrorPB_Code) EnumDescriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{2, 0}
}

type TSInformationPB_TSInfoType int32

const (
	TSInformationPB_UNKNOWN      TSInformationPB_TSInfoType = 0
	TSInformationPB_READ_REPLICA TSInformationPB_TSInfoType = 1
)

// Enum value maps for TSInformationPB_TSInfoType.
var (
	TSInformationPB_TSInfoType_name = map[int32]string{
		0: "UNKNOWN",
		1: "READ_REPLICA",
	}
	TSInformationPB_TSInfoType_value = map[string]int32{
		"UNKNOWN":      0,
		"READ_REPLICA": 1,
	}
)

func (x TSInformationPB_TSInfoType) Enum() *TSInformationPB_TSInfoType {
	p := new(TSInformationPB_TSInfoType)
	*p = x
	return p
}

func (x TSInformationPB_TSInfoType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TSInformationPB_TSInfoType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_master_cluster_proto_enumTypes[2].Descriptor()
}

func (TSInformationPB_TSInfoType) Type() protoreflect.EnumType {
	return &file_pb_master_cluster_proto_enumTypes[2]
}

func (x TSInformationPB_TSInfoType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TSInformationPB_TSInfoType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TSInformationPB_TSInfoType(num)
	return nil
}

// Deprecated: Use TSInformationPB_TSInfoType.Descriptor instead.
func (TSInformationPB_TSInfoType) EnumDescriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{8, 0}
}

type ListTabletServersRequestPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrimaryOnly   *bool                  `protobuf:"varint,1,opt,name=primary_only,json=primaryOnly,def=0" json:"primary_only,omitempty"`
	TablespaceId  []byte                 `protobuf:"bytes,2,opt,name=tablespace_id,json=tablespaceId" json:"tablespace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ListTabletServersRequestPB fields.
const (
	Default_ListTabletServersRequestPB_PrimaryOnly = bool(false)
)

func (x *ListTabletServersRequestPB) Reset() {
	*x = ListTabletServersRequestPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTabletServersRequestPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTabletServersRequestPB) ProtoMessage() {}

func (x *ListTabletServersRequestPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTabletServersRequestPB.ProtoReflect.Descriptor instead.
func (*ListTabletServersRequestPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *ListTabletServersRequestPB) GetPrimaryOnly() bool {
	if x != nil && x.PrimaryOnly != nil {
		return *x.PrimaryOnly
	}
	return Default_ListTabletServersRequestPB_PrimaryOnly
}

func (x *ListTabletServersRequestPB) GetTablespaceId() []byte {
	if x != nil {
		return x.TablespaceId
	}
	return nil
}

type ListTabletServersResponsePB struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Error         *MasterErrorPB                       `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Servers       []*ListTabletServersResponsePB_Entry `protobuf:"bytes,2,rep,name=servers" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTabletServersResponsePB) Reset() {
	*x = ListTabletServersResponsePB{}
	mi := &file_pb_master_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTabletServersResponsePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTabletServersResponsePB) ProtoMessage() {}

func (x *ListTabletServersResponsePB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTabletServersResponsePB.ProtoReflect.Descriptor instead.
func (*ListTabletServersResponsePB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *ListTabletServersResponsePB) GetError() *MasterErrorPB {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ListTabletServersResponsePB) GetServers() []*ListTabletServersResponsePB_Entry {
	if x != nil {
		return x.Servers
	}
	return nil
}

// Basic types needed for the response
type MasterErrorPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *MasterErrorPB_Code    `protobuf:"varint,1,req,name=code,enum=yb.master.MasterErrorPB_Code" json:"code,omitempty"`
	Status        *AppStatusPB           `protobuf:"bytes,2,req,name=status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterErrorPB) Reset() {
	*x = MasterErrorPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterErrorPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterErrorPB) ProtoMessage() {}

func (x *MasterErrorPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterErrorPB.ProtoReflect.Descriptor instead.
func (*MasterErrorPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *MasterErrorPB) GetCode() MasterErrorPB_Code {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return MasterErrorPB_UNKNOWN_ERROR
}

func (x *MasterErrorPB) GetStatus() *AppStatusPB {
	if x != nil {
		return x.Status
	}
	return nil
}

type AppStatusPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *int32                 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Message       *string                `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	PosixCode     *int32                 `protobuf:"varint,3,opt,name=posix_code,json=posixCode" json:"posix_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppStatusPB) Reset() {
	*x = AppStatusPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppStatusPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppStatusPB) ProtoMessage() {}

func (x *AppStatusPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppStatusPB.ProtoReflect.Descriptor instead.
func (*AppStatusPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *AppStatusPB) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *AppStatusPB) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *AppStatusPB) GetPosixCode() int32 {
	if x != nil && x.PosixCode != nil {
		return *x.PosixCode
	}
	return 0
}

type NodeInstancePB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermanentUuid []byte                 `protobuf:"bytes,1,req,name=permanent_uuid,json=permanentUuid" json:"permanent_uuid,omitempty"`
	InstanceSeqno *int64                 `protobuf:"varint,2,req,name=instance_seqno,json=instanceSeqno" json:"instance_seqno,omitempty"`
	StartTimeUs   *int64                 `protobuf:"varint,3,opt,name=start_time_us,json=startTimeUs" json:"start_time_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInstancePB) Reset() {
	*x = NodeInstancePB{}
	mi := &file_pb_master_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInstancePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInstancePB) ProtoMessage() {}

func (x *NodeInstancePB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInstancePB.ProtoReflect.Descriptor instead.
func (*NodeInstancePB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *NodeInstancePB) GetPermanentUuid() []byte {
	if x != nil {
		return x.PermanentUuid
	}
	return nil
}

func (x *NodeInstancePB) GetInstanceSeqno() int64 {
	if x != nil && x.InstanceSeqno != nil {
		return *x.InstanceSeqno
	}
	return 0
}

func (x *NodeInstancePB) GetStartTimeUs() int64 {
	if x != nil && x.StartTimeUs != nil {
		return *x.StartTimeUs
	}
	return 0
}

type TSRegistrationPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *ServerRegistrationPB  `protobuf:"bytes,1,opt,name=common" json:"common,omitempty"`
	Capabilities  []*TSInformationPB     `protobuf:"bytes,2,rep,name=capabilities" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TSRegistrationPB) Reset() {
	*x = TSRegistrationPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TSRegistrationPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TSRegistrationPB) ProtoMessage() {}

func (x *TSRegistrationPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TSRegistrationPB.ProtoReflect.Descriptor instead.
func (*TSRegistrationPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *TSRegistrationPB) GetCommon() *ServerRegistrationPB {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *TSRegistrationPB) GetCapabilities() []*TSInformationPB {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ServerRegistrationPB struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PrivateRpcAddresses []*HostPortPB          `protobuf:"bytes,1,rep,name=private_rpc_addresses,json=privateRpcAddresses" json:"private_rpc_addresses,omitempty"`
	BroadcastAddresses  []*HostPortPB          `protobuf:"bytes,2,rep,name=broadcast_addresses,json=broadcastAddresses" json:"broadcast_addresses,omitempty"`
	HttpAddresses       []*HostPortPB          `protobuf:"bytes,3,rep,name=http_addresses,json=httpAddresses" json:"http_addresses,omitempty"`
	PlacementCloud      *string                `protobuf:"bytes,4,opt,name=placement_cloud,json=placementCloud" json:"placement_cloud,omitempty"`
	PlacementRegion     *string                `protobuf:"bytes,5,opt,name=placement_region,json=placementRegion" json:"placement_region,omitempty"`
	PlacementZone       *string                `protobuf:"bytes,6,opt,name=placement_zone,json=placementZone" json:"placement_zone,omitempty"`
	PlacementUuid       []byte                 `protobuf:"bytes,7,opt,name=placement_uuid,json=placementUuid" json:"placement_uuid,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServerRegistrationPB) Reset() {
	*x = ServerRegistrationPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRegistrationPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRegistrationPB) ProtoMessage() {}

func (x *ServerRegistrationPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRegistrationPB.ProtoReflect.Descriptor instead.
func (*ServerRegistrationPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *ServerRegistrationPB) GetPrivateRpcAddresses() []*HostPortPB {
	if x != nil {
		return x.PrivateRpcAddresses
	}
	return nil
}

func (x *ServerRegistrationPB) GetBroadcastAddresses() []*HostPortPB {
	if x != nil {
		return x.BroadcastAddresses
	}
	return nil
}

func (x *ServerRegistrationPB) GetHttpAddresses() []*HostPortPB {
	if x != nil {
		return x.HttpAddresses
	}
	return nil
}

func (x *ServerRegistrationPB) GetPlacementCloud() string {
	if x != nil && x.PlacementCloud != nil {
		return *x.PlacementCloud
	}
	return ""
}

func (x *ServerRegistrationPB) GetPlacementRegion() string {
	if x != nil && x.PlacementRegion != nil {
		return *x.PlacementRegion
	}
	return ""
}

func (x *ServerRegistrationPB) GetPlacementZone() string {
	if x != nil && x.PlacementZone != nil {
		return *x.PlacementZone
	}
	return ""
}

func (x *ServerRegistrationPB) GetPlacementUuid() []byte {
	if x != nil {
		return x.PlacementUuid
	}
	return nil
}

type HostPortPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          *string                `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Port          *uint32                `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostPortPB) Reset() {
	*x = HostPortPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostPortPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostPortPB) ProtoMessage() {}

func (x *HostPortPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostPortPB.ProtoReflect.Descriptor instead.
func (*HostPortPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *HostPortPB) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *HostPortPB) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

type TSInformationPB struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	TserverType   *TSInformationPB_TSInfoType `protobuf:"varint,1,req,name=tserver_type,json=tserverType,enum=yb.master.TSInformationPB_TSInfoType" json:"tserver_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TSInformationPB) Reset() {
	*x = TSInformationPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TSInformationPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TSInformationPB) ProtoMessage() {}

func (x *TSInformationPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TSInformationPB.ProtoReflect.Descriptor instead.
func (*TSInformationPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *TSInformationPB) GetTserverType() TSInformationPB_TSInfoType {
	if x != nil && x.TserverType != nil {
		return *x.TserverType
	}
	return TSInformationPB_UNKNOWN
}

// ListMasters messages
type ListMastersRequestPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMastersRequestPB) Reset() {
	*x = ListMastersRequestPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMastersRequestPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMastersRequestPB) ProtoMessage() {}

func (x *ListMastersRequestPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMastersRequestPB.ProtoReflect.Descriptor instead.
func (*ListMastersRequestPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{9}
}

type ListMastersResponsePB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Masters       []*ServerEntryPB       `protobuf:"bytes,1,rep,name=masters" json:"masters,omitempty"`
	Error         *MasterErrorPB         `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMastersResponsePB) Reset() {
	*x = ListMastersResponsePB{}
	mi := &file_pb_master_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMastersResponsePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMastersResponsePB) ProtoMessage() {}

func (x *ListMastersResponsePB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMastersResponsePB.ProtoReflect.Descriptor instead.
func (*ListMastersResponsePB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *ListMastersResponsePB) GetMasters() []*ServerEntryPB {
	if x != nil {
		return x.Masters
	}
	return nil
}

func (x *ListMastersResponsePB) GetError() *MasterErrorPB {
	if x != nil {
		return x.Error
	}
	return nil
}

type ServerEntryPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *AppStatusPB           `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	InstanceId    *NodeInstancePB        `protobuf:"bytes,2,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
	Registration  *ServerRegistrationPB  `protobuf:"bytes,3,opt,name=registration" json:"registration,omitempty"`
	Role          *PeerRole              `protobuf:"varint,4,opt,name=role,enum=yb.master.PeerRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEntryPB) Reset() {
	*x = ServerEntryPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEntryPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEntryPB) ProtoMessage() {}

func (x *ServerEntryPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEntryPB.ProtoReflect.Descriptor instead.
func (*ServerEntryPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *ServerEntryPB) GetError() *AppStatusPB {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ServerEntryPB) GetInstanceId() *NodeInstancePB {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *ServerEntryPB) GetRegistration() *ServerRegistrationPB {
	if x != nil {
		return x.Registration
	}
	return nil
}

func (x *ServerEntryPB) GetRole() PeerRole {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return PeerRole_FOLLOWER
}

// GetMasterRegistration messages
type GetMasterRegistrationRequestPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMasterRegistrationRequestPB) Reset() {
	*x = GetMasterRegistrationRequestPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMasterRegistrationRequestPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMasterRegistrationRequestPB) ProtoMessage() {}

func (x *GetMasterRegistrationRequestPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMasterRegistrationRequestPB.ProtoReflect.Descriptor instead.
func (*GetMasterRegistrationRequestPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{12}
}

type GetMasterRegistrationResponsePB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    *NodeInstancePB        `protobuf:"bytes,1,req,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
	Registration  *ServerRegistrationPB  `protobuf:"bytes,2,opt,name=registration" json:"registration,omitempty"`
	Role          *PeerRole              `protobuf:"varint,3,opt,name=role,enum=yb.master.PeerRole" json:"role,omitempty"`
	Error         *MasterErrorPB         `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMasterRegistrationResponsePB) Reset() {
	*x = GetMasterRegistrationResponsePB{}
	mi := &file_pb_master_cluster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMasterRegistrationResponsePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMasterRegistrationResponsePB) ProtoMessage() {}

func (x *GetMasterRegistrationResponsePB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMasterRegistrationResponsePB.ProtoReflect.Descriptor instead.
func (*GetMasterRegistrationResponsePB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{13}
}

func (x *GetMasterRegistrationResponsePB) GetInstanceId() *NodeInstancePB {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *GetMasterRegistrationResponsePB) GetRegistration() *ServerRegistrationPB {
	if x != nil {
		return x.Registration
	}
	return nil
}

func (x *GetMasterRegistrationResponsePB) GetRole() PeerRole {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return PeerRole_FOLLOWER
}

func (x *GetMasterRegistrationResponsePB) GetError() *MasterErrorPB {
	if x != nil {
		return x.Error
	}
	return nil
}

// GetMasterClusterConfig messages
type GetMasterClusterConfigRequestPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMasterClusterConfigRequestPB) Reset() {
	*x = GetMasterClusterConfigRequestPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMasterClusterConfigRequestPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMasterClusterConfigRequestPB) ProtoMessage() {}

func (x *GetMasterClusterConfigRequestPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMasterClusterConfigRequestPB.ProtoReflect.Descriptor instead.
func (*GetMasterClusterConfigRequestPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{14}
}

type GetMasterClusterConfigResponsePB struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Error         *MasterErrorPB           `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	ClusterConfig *SysClusterConfigEntryPB `protobuf:"bytes,2,opt,name=cluster_config,json=clusterConfig" json:"cluster_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMasterClusterConfigResponsePB) Reset() {
	*x = GetMasterClusterConfigResponsePB{}
	mi := &file_pb_master_cluster_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMasterClusterConfigResponsePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMasterClusterConfigResponsePB) ProtoMessage() {}

func (x *GetMasterClusterConfigResponsePB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMasterClusterConfigResponsePB.ProtoReflect.Descriptor instead.
func (*GetMasterClusterConfigResponsePB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{15}
}

func (x *GetMasterClusterConfigResponsePB) GetError() *MasterErrorPB {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetMasterClusterConfigResponsePB) GetClusterConfig() *SysClusterConfigEntryPB {
	if x != nil {
		return x.ClusterConfig
	}
	return nil
}

type SysClusterConfigEntryPB struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          *int32                 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	ReplicationInfo  *ReplicationInfoPB     `protobuf:"bytes,2,opt,name=replication_info,json=replicationInfo" json:"replication_info,omitempty"`
	ServerBlacklist  *BlacklistPB           `protobuf:"bytes,3,opt,name=server_blacklist,json=serverBlacklist" json:"server_blacklist,omitempty"`
	ClusterUuid      *string                `protobuf:"bytes,4,opt,name=cluster_uuid,json=clusterUuid" json:"cluster_uuid,omitempty"`
	EncryptionInfo   *EncryptionInfoPB      `protobuf:"bytes,5,opt,name=encryption_info,json=encryptionInfo" json:"encryption_info,omitempty"`
	ConsumerRegistry []byte                 `protobuf:"bytes,6,opt,name=consumer_registry,json=consumerRegistry" json:"consumer_registry,omitempty"` // Simplified - we don't parse CDC info
	LeaderBlacklist  *BlacklistPB           `protobuf:"bytes,7,opt,name=leader_blacklist,json=leaderBlacklist" json:"leader_blacklist,omitempty"`
	UniverseUuid     *string                `protobuf:"bytes,8,opt,name=universe_uuid,json=universeUuid" json:"universe_uuid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SysClusterConfigEntryPB) Reset() {
	*x = SysClusterConfigEntryPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysClusterConfigEntryPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysClusterConfigEntryPB) ProtoMessage() {}

func (x *SysClusterConfigEntryPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysClusterConfigEntryPB.ProtoReflect.Descriptor instead.
func (*SysClusterConfigEntryPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{16}
}

func (x *SysClusterConfigEntryPB) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *SysClusterConfigEntryPB) GetReplicationInfo() *ReplicationInfoPB {
	if x != nil {
		return x.ReplicationInfo
	}
	return nil
}

func (x *SysClusterConfigEntryPB) GetServerBlacklist() *BlacklistPB {
	if x != nil {
		return x.ServerBlacklist
	}
	return nil
}

func (x *SysClusterConfigEntryPB) GetClusterUuid() string {
	if x != nil && x.ClusterUuid != nil {
		return *x.ClusterUuid
	}
	return ""
}

func (x *SysClusterConfigEntryPB) GetEncryptionInfo() *EncryptionInfoPB {
	if x != nil {
		return x.EncryptionInfo
	}
	return nil
}

func (x *SysClusterConfigEntryPB) GetConsumerRegistry() []byte {
	if x != nil {
		return x.ConsumerRegistry
	}
	return nil
}

func (x *SysClusterConfigEntryPB) GetLeaderBlacklist() *BlacklistPB {
	if x != nil {
		return x.LeaderBlacklist
	}
	return nil
}

func (x *SysClusterConfigEntryPB) GetUniverseUuid() string {
	if x != nil && x.UniverseUuid != nil {
		return *x.UniverseUuid
	}
	return ""
}

type BlacklistPB struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Hosts              []*HostPortPB          `protobuf:"bytes,1,rep,name=hosts" json:"hosts,omitempty"`
	InitialReplicaLoad *int32                 `protobuf:"varint,2,opt,name=initial_replica_load,json=initialReplicaLoad" json:"initial_replica_load,omitempty"`
	InitialLeaderLoad  *int32                 `protobuf:"varint,3,opt,name=initial_leader_load,json=initialLeaderLoad" json:"initial_leader_load,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BlacklistPB) Reset() {
	*x = BlacklistPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlacklistPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistPB) ProtoMessage() {}

func (x *BlacklistPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistPB.ProtoReflect.Descriptor instead.
func (*BlacklistPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{17}
}

func (x *BlacklistPB) GetHosts() []*HostPortPB {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *BlacklistPB) GetInitialReplicaLoad() int32 {
	if x != nil && x.InitialReplicaLoad != nil {
		return *x.InitialReplicaLoad
	}
	return 0
}

func (x *BlacklistPB) GetInitialLeaderLoad() int32 {
	if x != nil && x.InitialLeaderLoad != nil {
		return *x.InitialLeaderLoad
	}
	return 0
}

type ReplicationInfoPB struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	LiveReplicas            *PlacementInfoPB       `protobuf:"bytes,1,opt,name=live_replicas,json=liveReplicas" json:"live_replicas,omitempty"`
	ReadReplicas            []*PlacementInfoPB     `protobuf:"bytes,2,rep,name=read_replicas,json=readReplicas" json:"read_replicas,omitempty"`
	AffinitizedLeaders      []*CloudInfoPB         `protobuf:"bytes,3,rep,name=affinitized_leaders,json=affinitizedLeaders" json:"affinitized_leaders,omitempty"`
	MultiAffinitizedLeaders []*CloudInfoListPB     `protobuf:"bytes,4,rep,name=multi_affinitized_leaders,json=multiAffinitizedLeaders" json:"multi_affinitized_leaders,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ReplicationInfoPB) Reset() {
	*x = ReplicationInfoPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationInfoPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationInfoPB) ProtoMessage() {}

func (x *ReplicationInfoPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationInfoPB.ProtoReflect.Descriptor instead.
func (*ReplicationInfoPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{18}
}

func (x *ReplicationInfoPB) GetLiveReplicas() *PlacementInfoPB {
	if x != nil {
		return x.LiveReplicas
	}
	return nil
}

func (x *ReplicationInfoPB) GetReadReplicas() []*PlacementInfoPB {
	if x != nil {
		return x.ReadReplicas
	}
	return nil
}

func (x *ReplicationInfoPB) GetAffinitizedLeaders() []*CloudInfoPB {
	if x != nil {
		return x.AffinitizedLeaders
	}
	return nil
}

func (x *ReplicationInfoPB) GetMultiAffinitizedLeaders() []*CloudInfoListPB {
	if x != nil {
		return x.MultiAffinitizedLeaders
	}
	return nil
}

type CloudInfoListPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CloudInfos    []*CloudInfoPB         `protobuf:"bytes,1,rep,name=cloud_infos,json=cloudInfos" json:"cloud_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudInfoListPB) Reset() {
	*x = CloudInfoListPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudInfoListPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudInfoListPB) ProtoMessage() {}

func (x *CloudInfoListPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudInfoListPB.ProtoReflect.Descriptor instead.
func (*CloudInfoListPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{19}
}

func (x *CloudInfoListPB) GetCloudInfos() []*CloudInfoPB {
	if x != nil {
		return x.CloudInfos
	}
	return nil
}

type PlacementInfoPB struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NumReplicas     *int32                 `protobuf:"varint,1,opt,name=num_replicas,json=numReplicas" json:"num_replicas,omitempty"`
	PlacementBlocks []*PlacementBlockPB    `protobuf:"bytes,2,rep,name=placement_blocks,json=placementBlocks" json:"placement_blocks,omitempty"`
	PlacementUuid   []byte                 `protobuf:"bytes,3,opt,name=placement_uuid,json=placementUuid" json:"placement_uuid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlacementInfoPB) Reset() {
	*x = PlacementInfoPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacementInfoPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacementInfoPB) ProtoMessage() {}

func (x *PlacementInfoPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacementInfoPB.ProtoReflect.Descriptor instead.
func (*PlacementInfoPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{20}
}

func (x *PlacementInfoPB) GetNumReplicas() int32 {
	if x != nil && x.NumReplicas != nil {
		return *x.NumReplicas
	}
	return 0
}

func (x *PlacementInfoPB) GetPlacementBlocks() []*PlacementBlockPB {
	if x != nil {
		return x.PlacementBlocks
	}
	return nil
}

func (x *PlacementInfoPB) GetPlacementUuid() []byte {
	if x != nil {
		return x.PlacementUuid
	}
	return nil
}

type PlacementBlockPB struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CloudInfo      *CloudInfoPB           `protobuf:"bytes,1,opt,name=cloud_info,json=cloudInfo" json:"cloud_info,omitempty"`
	MinNumReplicas *int32                 `protobuf:"varint,2,opt,name=min_num_replicas,json=minNumReplicas" json:"min_num_replicas,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlacementBlockPB) Reset() {
	*x = PlacementBlockPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacementBlockPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacementBlockPB) ProtoMessage() {}

func (x *PlacementBlockPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacementBlockPB.ProtoReflect.Descriptor instead.
func (*PlacementBlockPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{21}
}

func (x *PlacementBlockPB) GetCloudInfo() *CloudInfoPB {
	if x != nil {
		return x.CloudInfo
	}
	return nil
}

func (x *PlacementBlockPB) GetMinNumReplicas() int32 {
	if x != nil && x.MinNumReplicas != nil {
		return *x.MinNumReplicas
	}
	return 0
}

type CloudInfoPB struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlacementCloud  *string                `protobuf:"bytes,1,opt,name=placement_cloud,json=placementCloud" json:"placement_cloud,omitempty"`
	PlacementRegion *string                `protobuf:"bytes,2,opt,name=placement_region,json=placementRegion" json:"placement_region,omitempty"`
	PlacementZone   *string                `protobuf:"bytes,3,opt,name=placement_zone,json=placementZone" json:"placement_zone,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CloudInfoPB) Reset() {
	*x = CloudInfoPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudInfoPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudInfoPB) ProtoMessage() {}

func (x *CloudInfoPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudInfoPB.ProtoReflect.Descriptor instead.
func (*CloudInfoPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{22}
}

func (x *CloudInfoPB) GetPlacementCloud() string {
	if x != nil && x.PlacementCloud != nil {
		return *x.PlacementCloud
	}
	return ""
}

func (x *CloudInfoPB) GetPlacementRegion() string {
	if x != nil && x.PlacementRegion != nil {
		return *x.PlacementRegion
	}
	return ""
}

func (x *CloudInfoPB) GetPlacementZone() string {
	if x != nil && x.PlacementZone != nil {
		return *x.PlacementZone
	}
	return ""
}

type EncryptionInfoPB struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	EncryptionEnabled          *bool                  `protobuf:"varint,1,opt,name=encryption_enabled,json=encryptionEnabled" json:"encryption_enabled,omitempty"`
	UniverseKeyRegistryEncoded []byte                 `protobuf:"bytes,2,opt,name=universe_key_registry_encoded,json=universeKeyRegistryEncoded" json:"universe_key_registry_encoded,omitempty"`
	KeyPath                    *string                `protobuf:"bytes,3,opt,name=key_path,json=keyPath" json:"key_path,omitempty"`
	LatestVersionId            *string                `protobuf:"bytes,4,opt,name=latest_version_id,json=latestVersionId" json:"latest_version_id,omitempty"`
	KeyInMemory                *bool                  `protobuf:"varint,5,opt,name=key_in_memory,json=keyInMemory" json:"key_in_memory,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *EncryptionInfoPB) Reset() {
	*x = EncryptionInfoPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptionInfoPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionInfoPB) ProtoMessage() {}

func (x *EncryptionInfoPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptionInfoPB.ProtoReflect.Descriptor instead.
func (*EncryptionInfoPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{23}
}

func (x *EncryptionInfoPB) GetEncryptionEnabled() bool {
	if x != nil && x.EncryptionEnabled != nil {
		return *x.EncryptionEnabled
	}
	return false
}

func (x *EncryptionInfoPB) GetUniverseKeyRegistryEncoded() []byte {
	if x != nil {
		return x.UniverseKeyRegistryEncoded
	}
	return nil
}

func (x *EncryptionInfoPB) GetKeyPath() string {
	if x != nil && x.KeyPath != nil {
		return *x.KeyPath
	}
	return ""
}

func (x *EncryptionInfoPB) GetLatestVersionId() string {
	if x != nil && x.LatestVersionId != nil {
		return *x.LatestVersionId
	}
	return ""
}

func (x *EncryptionInfoPB) GetKeyInMemory() bool {
	if x != nil && x.KeyInMemory != nil {
		return *x.KeyInMemory
	}
	return false
}

// Connection context message
type ConnectionContextPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *UserInformationPB     `protobuf:"bytes,1,opt,name=user_info,json=userInfo" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionContextPB) Reset() {
	*x = ConnectionContextPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionContextPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionContextPB) ProtoMessage() {}

func (x *ConnectionContextPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionContextPB.ProtoReflect.Descriptor instead.
func (*ConnectionContextPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{24}
}

func (x *ConnectionContextPB) GetUserInfo() *UserInformationPB {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type UserInformationPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EffectiveUser *string                `protobuf:"bytes,1,opt,name=effective_user,json=effectiveUser" json:"effective_user,omitempty"`
	RealUser      *string                `protobuf:"bytes,2,opt,name=real_user,json=realUser" json:"real_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInformationPB) Reset() {
	*x = UserInformationPB{}
	mi := &file_pb_master_cluster_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInformationPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInformationPB) ProtoMessage() {}

func (x *UserInformationPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInformationPB.ProtoReflect.Descriptor instead.
func (*UserInformationPB) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{25}
}

func (x *UserInformationPB) GetEffectiveUser() string {
	if x != nil && x.EffectiveUser != nil {
		return *x.EffectiveUser
	}
	return ""
}

func (x *UserInformationPB) GetRealUser() string {
	if x != nil && x.RealUser != nil {
		return *x.RealUser
	}
	return ""
}

type ListTabletServersResponsePB_Entry struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	InstanceId           *NodeInstancePB        `protobuf:"bytes,1,req,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
	Registration         *TSRegistrationPB      `protobuf:"bytes,2,opt,name=registration" json:"registration,omitempty"`
	MillisSinceHeartbeat *int32                 `protobuf:"varint,3,opt,name=millis_since_heartbeat,json=millisSinceHeartbeat" json:"millis_since_heartbeat,omitempty"`
	Alive                *bool                  `protobuf:"varint,4,opt,name=alive" json:"alive,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListTabletServersResponsePB_Entry) Reset() {
	*x = ListTabletServersResponsePB_Entry{}
	mi := &file_pb_master_cluster_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTabletServersResponsePB_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTabletServersResponsePB_Entry) ProtoMessage() {}

func (x *ListTabletServersResponsePB_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_pb_master_cluster_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTabletServersResponsePB_Entry.ProtoReflect.Descriptor instead.
func (*ListTabletServersResponsePB_Entry) Descriptor() ([]byte, []int) {
	return file_pb_master_cluster_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListTabletServersResponsePB_Entry) GetInstanceId() *NodeInstancePB {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *ListTabletServersResponsePB_Entry) GetRegistration() *TSRegistrationPB {
	if x != nil {
		return x.Registration
	}
	return nil
}

func (x *ListTabletServersResponsePB_Entry) GetMillisSinceHeartbeat() int32 {
	if x != nil && x.MillisSinceHeartbeat != nil {
		return *x.MillisSinceHeartbeat
	}
	return 0
}

func (x *ListTabletServersResponsePB_Entry) GetAlive() bool {
	if x != nil && x.Alive != nil {
		return *x.Alive
	}
	return false
}

var File_pb_master_cluster_proto protoreflect.FileDescriptor

const file_pb_master_cluster_proto_rawDesc = "" +
	"\n" +
	"\x17pb/master_cluster.proto\x12\tyb.master\"k\n" +
	"\x1aListTabletServersRequestPB\x12(\n" +
	"\fprimary_only\x18\x01 \x01(\b:\x05falseR\vprimaryOnly\x12#\n" +
	"\rtablespace_id\x18\x02 \x01(\fR\ftablespaceId\"\xe8\x02\n" +
	"\x1bListTabletServersResponsePB\x12.\n" +
	"\x05error\x18\x01 \x01(\v2\x18.yb.master.MasterErrorPBR\x05error\x12F\n" +
	"\aservers\x18\x02 \x03(\v2,.yb.master.ListTabletServersResponsePB.EntryR\aservers\x1a\xd0\x01\n" +
	"\x05Entry\x12:\n" +
	"\vinstance_id\x18\x01 \x02(\v2\x19.yb.master.NodeInstancePBR\n" +
	"instanceId\x12?\n" +
	"\fregistration\x18\x02 \x01(\v2\x1b.yb.master.TSRegistrationPBR\fregistration\x124\n" +
	"\x16millis_since_heartbeat\x18\x03 \x01(\x05R\x14millisSinceHeartbeat\x12\x14\n" +
	"\x05alive\x18\x04 \x01(\bR\x05alive\"\xb4\x01\n" +
	"\rMasterErrorPB\x121\n" +
	"\x04code\x18\x01 \x02(\x0e2\x1d.yb.master.MasterErrorPB.CodeR\x04code\x12.\n" +
	"\x06status\x18\x02 \x02(\v2\x16.yb.master.AppStatusPBR\x06status\"@\n" +
	"\x04Code\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x01\x12\x11\n" +
	"\rINVALID_TABLE\x10\x02\x12\x12\n" +
	"\x0eNOT_THE_LEADER\x10\x03\"Z\n" +
	"\vAppStatusPB\x12\x12\n" +
	"\x04code\x18\x01 \x02(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x02(\tR\amessage\x12\x1d\n" +
	"\n" +
	"posix_code\x18\x03 \x01(\x05R\tposixCode\"\x82\x01\n" +
	"\x0eNodeInstancePB\x12%\n" +
	"\x0epermanent_uuid\x18\x01 \x02(\fR\rpermanentUuid\x12%\n" +
	"\x0einstance_seqno\x18\x02 \x02(\x03R\rinstanceSeqno\x12\"\n" +
	"\rstart_time_us\x18\x03 \x01(\x03R\vstartTimeUs\"\x8b\x01\n" +
	"\x10TSRegistrationPB\x127\n" +
	"\x06common\x18\x01 \x01(\v2\x1f.yb.master.ServerRegistrationPBR\x06common\x12>\n" +
	"\fcapabilities\x18\x02 \x03(\v2\x1a.yb.master.TSInformationPBR\fcapabilities\"\x89\x03\n" +
	"\x14ServerRegistrationPB\x12I\n" +
	"\x15private_rpc_addresses\x18\x01 \x03(\v2\x15.yb.master.HostPortPBR\x13privateRpcAddresses\x12F\n" +
	"\x13broadcast_addresses\x18\x02 \x03(\v2\x15.yb.master.HostPortPBR\x12broadcastAddresses\x12<\n" +
	"\x0ehttp_addresses\x18\x03 \x03(\v2\x15.yb.master.HostPortPBR\rhttpAddresses\x12'\n" +
	"\x0fplacement_cloud\x18\x04 \x01(\tR\x0eplacementCloud\x12)\n" +
	"\x10placement_region\x18\x05 \x01(\tR\x0fplacementRegion\x12%\n" +
	"\x0eplacement_zone\x18\x06 \x01(\tR\rplacementZone\x12%\n" +
	"\x0eplacement_uuid\x18\a \x01(\fR\rplacementUuid\"4\n" +
	"\n" +
	"HostPortPB\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\x88\x01\n" +
	"\x0fTSInformationPB\x12H\n" +
	"\ftserver_type\x18\x01 \x02(\x0e2%.yb.master.TSInformationPB.TSInfoTypeR\vtserverType\"+\n" +
	"\n" +
	"TSInfoType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x10\n" +
	"\fREAD_REPLICA\x10\x01\"\x16\n" +
	"\x14ListMastersRequestPB\"{\n" +
	"\x15ListMastersResponsePB\x122\n" +
	"\amasters\x18\x01 \x03(\v2\x18.yb.master.ServerEntryPBR\amasters\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x18.yb.master.MasterErrorPBR\x05error\"\xe7\x01\n" +
	"\rServerEntryPB\x12,\n" +
	"\x05error\x18\x01 \x01(\v2\x16.yb.master.AppStatusPBR\x05error\x12:\n" +
	"\vinstance_id\x18\x02 \x01(\v2\x19.yb.master.NodeInstancePBR\n" +
	"instanceId\x12C\n" +
	"\fregistration\x18\x03 \x01(\v2\x1f.yb.master.ServerRegistrationPBR\fregistration\x12'\n" +
	"\x04role\x18\x04 \x01(\x0e2\x13.yb.master.PeerRoleR\x04role\" \n" +
	"\x1eGetMasterRegistrationRequestPB\"\xfb\x01\n" +
	"\x1fGetMasterRegistrationResponsePB\x12:\n" +
	"\vinstance_id\x18\x01 \x02(\v2\x19.yb.master.NodeInstancePBR\n" +
	"instanceId\x12C\n" +
	"\fregistration\x18\x02 \x01(\v2\x1f.yb.master.ServerRegistrationPBR\fregistration\x12'\n" +
	"\x04role\x18\x03 \x01(\x0e2\x13.yb.master.PeerRoleR\x04role\x12.\n" +
	"\x05error\x18\x04 \x01(\v2\x18.yb.master.MasterErrorPBR\x05error\"!\n" +
	"\x1fGetMasterClusterConfigRequestPB\"\x9d\x01\n" +
	" GetMasterClusterConfigResponsePB\x12.\n" +
	"\x05error\x18\x01 \x01(\v2\x18.yb.master.MasterErrorPBR\x05error\x12I\n" +
	"\x0ecluster_config\x18\x02 \x01(\v2\".yb.master.SysClusterConfigEntryPBR\rclusterConfig\"\xbd\x03\n" +
	"\x17SysClusterConfigEntryPB\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12G\n" +
	"\x10replication_info\x18\x02 \x01(\v2\x1c.yb.master.ReplicationInfoPBR\x0freplicationInfo\x12A\n" +
	"\x10server_blacklist\x18\x03 \x01(\v2\x16.yb.master.BlacklistPBR\x0fserverBlacklist\x12!\n" +
	"\fcluster_uuid\x18\x04 \x01(\tR\vclusterUuid\x12D\n" +
	"\x0fencryption_info\x18\x05 \x01(\v2\x1b.yb.master.EncryptionInfoPBR\x0eencryptionInfo\x12+\n" +
	"\x11consumer_registry\x18\x06 \x01(\fR\x10consumerRegistry\x12A\n" +
	"\x10leader_blacklist\x18\a \x01(\v2\x16.yb.master.BlacklistPBR\x0fleaderBlacklist\x12#\n" +
	"\runiverse_uuid\x18\b \x01(\tR\funiverseUuid\"\x9c\x01\n" +
	"\vBlacklistPB\x12+\n" +
	"\x05hosts\x18\x01 \x03(\v2\x15.yb.master.HostPortPBR\x05hosts\x120\n" +
	"\x14initial_replica_load\x18\x02 \x01(\x05R\x12initialReplicaLoad\x12.\n" +
	"\x13initial_leader_load\x18\x03 \x01(\x05R\x11initialLeaderLoad\"\xb6\x02\n" +
	"\x11ReplicationInfoPB\x12?\n" +
	"\rlive_replicas\x18\x01 \x01(\v2\x1a.yb.master.PlacementInfoPBR\fliveReplicas\x12?\n" +
	"\rread_replicas\x18\x02 \x03(\v2\x1a.yb.master.PlacementInfoPBR\freadReplicas\x12G\n" +
	"\x13affinitized_leaders\x18\x03 \x03(\v2\x16.yb.master.CloudInfoPBR\x12affinitizedLeaders\x12V\n" +
	"\x19multi_affinitized_leaders\x18\x04 \x03(\v2\x1a.yb.master.CloudInfoListPBR\x17multiAffinitizedLeaders\"J\n" +
	"\x0fCloudInfoListPB\x127\n" +
	"\vcloud_infos\x18\x01 \x03(\v2\x16.yb.master.CloudInfoPBR\n" +
	"cloudInfos\"\xa3\x01\n" +
	"\x0fPlacementInfoPB\x12!\n" +
	"\fnum_replicas\x18\x01 \x01(\x05R\vnumReplicas\x12F\n" +
	"\x10placement_blocks\x18\x02 \x03(\v2\x1b.yb.master.PlacementBlockPBR\x0fplacementBlocks\x12%\n" +
	"\x0eplacement_uuid\x18\x03 \x01(\fR\rplacementUuid\"s\n" +
	"\x10PlacementBlockPB\x125\n" +
	"\n" +
	"cloud_info\x18\x01 \x01(\v2\x16.yb.master.CloudInfoPBR\tcloudInfo\x12(\n" +
	"\x10min_num_replicas\x18\x02 \x01(\x05R\x0eminNumReplicas\"\x88\x01\n" +
	"\vCloudInfoPB\x12'\n" +
	"\x0fplacement_cloud\x18\x01 \x01(\tR\x0eplacementCloud\x12)\n" +
	"\x10placement_region\x18\x02 \x01(\tR\x0fplacementRegion\x12%\n" +
	"\x0eplacement_zone\x18\x03 \x01(\tR\rplacementZone\"\xef\x01\n" +
	"\x10EncryptionInfoPB\x12-\n" +
	"\x12encryption_enabled\x18\x01 \x01(\bR\x11encryptionEnabled\x12A\n" +
	"\x1duniverse_key_registry_encoded\x18\x02 \x01(\fR\x1auniverseKeyRegistryEncoded\x12\x19\n" +
	"\bkey_path\x18\x03 \x01(\tR\akeyPath\x12*\n" +
	"\x11latest_version_id\x18\x04 \x01(\tR\x0flatestVersionId\x12\"\n" +
	"\rkey_in_memory\x18\x05 \x01(\bR\vkeyInMemory\"P\n" +
	"\x13ConnectionContextPB\x129\n" +
	"\tuser_info\x18\x01 \x01(\v2\x1c.yb.master.UserInformationPBR\buserInfo\"W\n" +
	"\x11UserInformationPB\x12%\n" +
	"\x0eeffective_user\x18\x01 \x01(\tR\reffectiveUser\x12\x1b\n" +
	"\treal_user\x18\x02 \x01(\tR\brealUser*F\n" +
	"\bPeerRole\x12\f\n" +
	"\bFOLLOWER\x10\x00\x12\n" +
	"\n" +
	"\x06LEADER\x10\x01\x12\r\n" +
	"\tCANDIDATE\x10\x02\x12\x11\n" +
	"\fUNKNOWN_ROLE\x10\xe7\aB8Z6github.com/Shopify/yugabyte-db/shopify-yb-client/pb;pb"

var (
	file_pb_master_cluster_proto_rawDescOnce sync.Once
	file_pb_master_cluster_proto_rawDescData []byte
)

func file_pb_master_cluster_proto_rawDescGZIP() []byte {
	file_pb_master_cluster_proto_rawDescOnce.Do(func() {
		file_pb_master_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_master_cluster_proto_rawDesc), len(file_pb_master_cluster_proto_rawDesc)))
	})
	return file_pb_master_cluster_proto_rawDescData
}

var file_pb_master_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pb_master_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_pb_master_cluster_proto_goTypes = []any{
	(PeerRole)(0),                             // 0: yb.master.PeerRole
	(MasterErrorPB_Code)(0),                   // 1: yb.master.MasterErrorPB.Code
	(TSInformationPB_TSInfoType)(0),           // 2: yb.master.TSInformationPB.TSInfoType
	(*ListTabletServersRequestPB)(nil),        // 3: yb.master.ListTabletServersRequestPB
	(*ListTabletServersResponsePB)(nil),       // 4: yb.master.ListTabletServersResponsePB
	(*MasterErrorPB)(nil),                     // 5: yb.master.MasterErrorPB
	(*AppStatusPB)(nil),                       // 6: yb.master.AppStatusPB
	(*NodeInstancePB)(nil),                    // 7: yb.master.NodeInstancePB
	(*TSRegistrationPB)(nil),                  // 8: yb.master.TSRegistrationPB
	(*ServerRegistrationPB)(nil),              // 9: yb.master.ServerRegistrationPB
	(*HostPortPB)(nil),                        // 10: yb.master.HostPortPB
	(*TSInformationPB)(nil),                   // 11: yb.master.TSInformationPB
	(*ListMastersRequestPB)(nil),              // 12: yb.master.ListMastersRequestPB
	(*ListMastersResponsePB)(nil),             // 13: yb.master.ListMastersResponsePB
	(*ServerEntryPB)(nil),                     // 14: yb.master.ServerEntryPB
	(*GetMasterRegistrationRequestPB)(nil),    // 15: yb.master.GetMasterRegistrationRequestPB
	(*GetMasterRegistrationResponsePB)(nil),   // 16: yb.master.GetMasterRegistrationResponsePB
	(*GetMasterClusterConfigRequestPB)(nil),   // 17: yb.master.GetMasterClusterConfigRequestPB
	(*GetMasterClusterConfigResponsePB)(nil),  // 18: yb.master.GetMasterClusterConfigResponsePB
	(*SysClusterConfigEntryPB)(nil),           // 19: yb.master.SysClusterConfigEntryPB
	(*BlacklistPB)(nil),                       // 20: yb.master.BlacklistPB
	(*ReplicationInfoPB)(nil),                 // 21: yb.master.ReplicationInfoPB
	(*CloudInfoListPB)(nil),                   // 22: yb.master.CloudInfoListPB
	(*PlacementInfoPB)(nil),                   // 23: yb.master.PlacementInfoPB
	(*PlacementBlockPB)(nil),                  // 24: yb.master.PlacementBlockPB
	(*CloudInfoPB)(nil),                       // 25: yb.master.CloudInfoPB
	(*EncryptionInfoPB)(nil),                  // 26: yb.master.EncryptionInfoPB
	(*ConnectionContextPB)(nil),               // 27: yb.master.ConnectionContextPB
	(*UserInformationPB)(nil),                 // 28: yb.master.UserInformationPB
	(*ListTabletServersResponsePB_Entry)(nil), // 29: yb.master.ListTabletServersResponsePB.Entry
}
var file_pb_master_cluster_proto_depIdxs = []int32{
	5,  // 0: yb.master.ListTabletServersResponsePB.error:type_name -> yb.master.MasterErrorPB
	29, // 1: yb.master.ListTabletServersResponsePB.servers:type_name -> yb.master.ListTabletServersResponsePB.Entry
	1,  // 2: yb.master.MasterErrorPB.code:type_name -> yb.master.MasterErrorPB.Code
	6,  // 3: yb.master.MasterErrorPB.status:type_name -> yb.master.AppStatusPB
	9,  // 4: yb.master.TSRegistrationPB.common:type_name -> yb.master.ServerRegistrationPB
	11, // 5: yb.master.TSRegistrationPB.capabilities:type_name -> yb.master.TSInformationPB
	10, // 6: yb.master.ServerRegistrationPB.private_rpc_addresses:type_name -> yb.master.HostPortPB
	10, // 7: yb.master.ServerRegistrationPB.broadcast_addresses:type_name -> yb.master.HostPortPB
	10, // 8: yb.master.ServerRegistrationPB.http_addresses:type_name -> yb.master.HostPortPB
	2,  // 9: yb.master.TSInformationPB.tserver_type:type_name -> yb.master.TSInformationPB.TSInfoType
	14, // 10: yb.master.ListMastersResponsePB.masters:type_name -> yb.master.ServerEntryPB
	5,  // 11: yb.master.ListMastersResponsePB.error:type_name -> yb.master.MasterErrorPB
	6,  // 12: yb.master.ServerEntryPB.error:type_name -> yb.master.AppStatusPB
	7,  // 13: yb.master.ServerEntryPB.instance_id:type_name -> yb.master.NodeInstancePB
	9,  // 14: yb.master.ServerEntryPB.registration:type_name -> yb.master.ServerRegistrationPB
	0,  // 15: yb.master.ServerEntryPB.role:type_name -> yb.master.PeerRole
	7,  // 16: yb.master.GetMasterRegistrationResponsePB.instance_id:type_name -> yb.master.NodeInstancePB
	9,  // 17: yb.master.GetMasterRegistrationResponsePB.registration:type_name -> yb.master.ServerRegistrationPB
	0,  // 18: yb.master.GetMasterRegistrationResponsePB.role:type_name -> yb.master.PeerRole
	5,  // 19: yb.master.GetMasterRegistrationResponsePB.error:type_name -> yb.master.MasterErrorPB
	5,  // 20: yb.master.GetMasterClusterConfigResponsePB.error:type_name -> yb.master.MasterErrorPB
	19, // 21: yb.master.GetMasterClusterConfigResponsePB.cluster_config:type_name -> yb.master.SysClusterConfigEntryPB
	21, // 22: yb.master.SysClusterConfigEntryPB.replication_info:type_name -> yb.master.ReplicationInfoPB
	20, // 23: yb.master.SysClusterConfigEntryPB.server_blacklist:type_name -> yb.master.BlacklistPB
	26, // 24: yb.master.SysClusterConfigEntryPB.encryption_info:type_name -> yb.master.EncryptionInfoPB
	20, // 25: yb.master.SysClusterConfigEntryPB.leader_blacklist:type_name -> yb.master.BlacklistPB
	10, // 26: yb.master.BlacklistPB.hosts:type_name -> yb.master.HostPortPB
	23, // 27: yb.master.ReplicationInfoPB.live_replicas:type_name -> yb.master.PlacementInfoPB
	23, // 28: yb.master.ReplicationInfoPB.read_replicas:type_name -> yb.master.PlacementInfoPB
	25, // 29: yb.master.ReplicationInfoPB.affinitized_leaders:type_name -> yb.master.CloudInfoPB
	22, // 30: yb.master.ReplicationInfoPB.multi_affinitized_leaders:type_name -> yb.master.CloudInfoListPB
	25, // 31: yb.master.CloudInfoListPB.cloud_infos:type_name -> yb.master.CloudInfoPB
	24, // 32: yb.master.PlacementInfoPB.placement_blocks:type_name -> yb.master.PlacementBlockPB
	25, // 33: yb.master.PlacementBlockPB.cloud_info:type_name -> yb.master.CloudInfoPB
	28, // 34: yb.master.ConnectionContextPB.user_info:type_name -> yb.master.UserInformationPB
	7,  // 35: yb.master.ListTabletServersResponsePB.Entry.instance_id:type_name -> yb.master.NodeInstancePB
	8,  // 36: yb.master.ListTabletServersResponsePB.Entry.registration:type_name -> yb.master.TSRegistrationPB
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_pb_master_cluster_proto_init() }
func file_pb_master_cluster_proto_init() {
	if File_pb_master_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_master_cluster_proto_rawDesc), len(file_pb_master_cluster_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_master_cluster_proto_goTypes,
		DependencyIndexes: file_pb_master_cluster_proto_depIdxs,
		EnumInfos:         file_pb_master_cluster_proto_enumTypes,
		MessageInfos:      file_pb_master_cluster_proto_msgTypes,
	}.Build()
	File_pb_master_cluster_proto = out.File
	file_pb_master_cluster_proto_goTypes = nil
	file_pb_master_cluster_proto_depIdxs = nil
}
