// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pb/rpc_header.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteMethodPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   *string                `protobuf:"bytes,1,req,name=service_name,json=serviceName" json:"service_name,omitempty"`
	MethodName    *string                `protobuf:"bytes,2,req,name=method_name,json=methodName" json:"method_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteMethodPB) Reset() {
	*x = RemoteMethodPB{}
	mi := &file_pb_rpc_header_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteMethodPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteMethodPB) ProtoMessage() {}

func (x *RemoteMethodPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_header_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteMethodPB.ProtoReflect.Descriptor instead.
func (*RemoteMethodPB) Descriptor() ([]byte, []int) {
	return file_pb_rpc_header_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteMethodPB) GetServiceName() string {
	if x != nil && x.ServiceName != nil {
		return *x.ServiceName
	}
	return ""
}

func (x *RemoteMethodPB) GetMethodName() string {
	if x != nil && x.MethodName != nil {
		return *x.MethodName
	}
	return ""
}

type RequestHeader struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CallId         *int32                 `protobuf:"varint,1,opt,name=call_id,json=callId" json:"call_id,omitempty"`
	RemoteMethod   *RemoteMethodPB        `protobuf:"bytes,2,opt,name=remote_method,json=remoteMethod" json:"remote_method,omitempty"`
	TimeoutMillis  *uint32                `protobuf:"varint,3,opt,name=timeout_millis,json=timeoutMillis" json:"timeout_millis,omitempty"`
	SidecarOffsets []uint32               `protobuf:"fixed32,4,rep,packed,name=sidecar_offsets,json=sidecarOffsets" json:"sidecar_offsets,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestHeader) Reset() {
	*x = RequestHeader{}
	mi := &file_pb_rpc_header_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHeader) ProtoMessage() {}

func (x *RequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_header_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHeader.ProtoReflect.Descriptor instead.
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return file_pb_rpc_header_proto_rawDescGZIP(), []int{1}
}

func (x *RequestHeader) GetCallId() int32 {
	if x != nil && x.CallId != nil {
		return *x.CallId
	}
	return 0
}

func (x *RequestHeader) GetRemoteMethod() *RemoteMethodPB {
	if x != nil {
		return x.RemoteMethod
	}
	return nil
}

func (x *RequestHeader) GetTimeoutMillis() uint32 {
	if x != nil && x.TimeoutMillis != nil {
		return *x.TimeoutMillis
	}
	return 0
}

func (x *RequestHeader) GetSidecarOffsets() []uint32 {
	if x != nil {
		return x.SidecarOffsets
	}
	return nil
}

type ResponseHeader struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CallId         *int32                 `protobuf:"varint,1,req,name=call_id,json=callId" json:"call_id,omitempty"`
	IsError        *bool                  `protobuf:"varint,2,opt,name=is_error,json=isError,def=0" json:"is_error,omitempty"`
	SidecarOffsets []uint32               `protobuf:"varint,3,rep,name=sidecar_offsets,json=sidecarOffsets" json:"sidecar_offsets,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

// Default values for ResponseHeader fields.
const (
	Default_ResponseHeader_IsError = bool(false)
)

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	mi := &file_pb_rpc_header_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_header_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_pb_rpc_header_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseHeader) GetCallId() int32 {
	if x != nil && x.CallId != nil {
		return *x.CallId
	}
	return 0
}

func (x *ResponseHeader) GetIsError() bool {
	if x != nil && x.IsError != nil {
		return *x.IsError
	}
	return Default_ResponseHeader_IsError
}

func (x *ResponseHeader) GetSidecarOffsets() []uint32 {
	if x != nil {
		return x.SidecarOffsets
	}
	return nil
}

type ErrorStatusPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *string                `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	Code          *int32                 `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	PosixCode     *int32                 `protobuf:"varint,3,opt,name=posix_code,json=posixCode" json:"posix_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorStatusPB) Reset() {
	*x = ErrorStatusPB{}
	mi := &file_pb_rpc_header_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorStatusPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorStatusPB) ProtoMessage() {}

func (x *ErrorStatusPB) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_header_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorStatusPB.ProtoReflect.Descriptor instead.
func (*ErrorStatusPB) Descriptor() ([]byte, []int) {
	return file_pb_rpc_header_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorStatusPB) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ErrorStatusPB) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *ErrorStatusPB) GetPosixCode() int32 {
	if x != nil && x.PosixCode != nil {
		return *x.PosixCode
	}
	return 0
}

var File_pb_rpc_header_proto protoreflect.FileDescriptor

const file_pb_rpc_header_proto_rawDesc = "" +
	"\n" +
	"\x13pb/rpc_header.proto\x12\x06yb.rpc\"T\n" +
	"\x0eRemoteMethodPB\x12!\n" +
	"\fservice_name\x18\x01 \x02(\tR\vserviceName\x12\x1f\n" +
	"\vmethod_name\x18\x02 \x02(\tR\n" +
	"methodName\"\xb9\x01\n" +
	"\rRequestHeader\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\x05R\x06callId\x12;\n" +
	"\rremote_method\x18\x02 \x01(\v2\x16.yb.rpc.RemoteMethodPBR\fremoteMethod\x12%\n" +
	"\x0etimeout_millis\x18\x03 \x01(\rR\rtimeoutMillis\x12+\n" +
	"\x0fsidecar_offsets\x18\x04 \x03(\aB\x02\x10\x01R\x0esidecarOffsets\"t\n" +
	"\x0eResponseHeader\x12\x17\n" +
	"\acall_id\x18\x01 \x02(\x05R\x06callId\x12 \n" +
	"\bis_error\x18\x02 \x01(\b:\x05falseR\aisError\x12'\n" +
	"\x0fsidecar_offsets\x18\x03 \x03(\rR\x0esidecarOffsets\"\\\n" +
	"\rErrorStatusPB\x12\x18\n" +
	"\amessage\x18\x01 \x02(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x1d\n" +
	"\n" +
	"posix_code\x18\x03 \x01(\x05R\tposixCodeB8Z6github.com/Shopify/yugabyte-db/shopify-yb-client/pb;pb"

var (
	file_pb_rpc_header_proto_rawDescOnce sync.Once
	file_pb_rpc_header_proto_rawDescData []byte
)

func file_pb_rpc_header_proto_rawDescGZIP() []byte {
	file_pb_rpc_header_proto_rawDescOnce.Do(func() {
		file_pb_rpc_header_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_rpc_header_proto_rawDesc), len(file_pb_rpc_header_proto_rawDesc)))
	})
	return file_pb_rpc_header_proto_rawDescData
}

var file_pb_rpc_header_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_rpc_header_proto_goTypes = []any{
	(*RemoteMethodPB)(nil), // 0: yb.rpc.RemoteMethodPB
	(*RequestHeader)(nil),  // 1: yb.rpc.RequestHeader
	(*ResponseHeader)(nil), // 2: yb.rpc.ResponseHeader
	(*ErrorStatusPB)(nil),  // 3: yb.rpc.ErrorStatusPB
}
var file_pb_rpc_header_proto_depIdxs = []int32{
	0, // 0: yb.rpc.RequestHeader.remote_method:type_name -> yb.rpc.RemoteMethodPB
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_rpc_header_proto_init() }
func file_pb_rpc_header_proto_init() {
	if File_pb_rpc_header_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_rpc_header_proto_rawDesc), len(file_pb_rpc_header_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_rpc_header_proto_goTypes,
		DependencyIndexes: file_pb_rpc_header_proto_depIdxs,
		MessageInfos:      file_pb_rpc_header_proto_msgTypes,
	}.Build()
	File_pb_rpc_header_proto = out.File
	file_pb_rpc_header_proto_goTypes = nil
	file_pb_rpc_header_proto_depIdxs = nil
}
